#!/usr/bin/env python3
"""Universal theme applier — reads a theme JSON, generates configs for all detected targets."""

import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
THEME_DIR = os.path.join(BASE_DIR, "themes")
BACKUP_DIR = os.path.join(BASE_DIR, "backups")
CURRENT_FILE = os.path.join(BASE_DIR, "current-theme")
HOME = os.path.expanduser("~")

# ── Target config paths ──────────────────────────────────────────────────────

HYPRLAND_COLORS = os.path.join(HOME, ".config/hypr/dms/colors.conf")
DMS_THEMES_DIR = os.path.join(HOME, ".config/DankMaterialShell/themes")
DMS_SETTINGS = os.path.join(HOME, ".config/DankMaterialShell/settings.json")
NOCTALIA_SCHEMES_DIR = os.path.join(HOME, ".config/noctalia/colorschemes")
NOCTALIA_SETTINGS = os.path.join(HOME, ".config/noctalia/settings.json")
DUNST_CONFIG = os.path.join(HOME, ".config/dunst/dunstrc")
ROFI_CONFIG = os.path.join(HOME, ".config/rofi/config.rasi")
SWAYNC_CSS = os.path.join(HOME, ".config/swaync/style.css")
CHADWM_THEMES_DIR = os.path.join(HOME, ".config/arco-chadwm/chadwm/themes")
CHADWM_CONFIG = os.path.join(HOME, ".config/arco-chadwm/chadwm/config.def.h")


# ── Helpers ───────────────────────────────────────────────────────────────────

def strip_hash(hex_color):
    """'#ff5555' → 'ff5555'"""
    return hex_color.lstrip("#")


def hex_alpha(hex_color, alpha="dd"):
    """'#ff5555' → '#ff5555dd'"""
    return hex_color + alpha


def is_running(process_name):
    """Check if a process is running."""
    try:
        subprocess.check_output(["pgrep", "-x", process_name],
                                stderr=subprocess.DEVNULL)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def darken(hex_color, amount=0.15):
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    f = 1.0 - amount
    return "#{:02x}{:02x}{:02x}".format(int(r * f), int(g * f), int(b * f))


def lighten(hex_color, amount=0.15):
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    r = min(255, int(r + (255 - r) * amount))
    g = min(255, int(g + (255 - g) * amount))
    b = min(255, int(b + (255 - b) * amount))
    return "#{:02x}{:02x}{:02x}".format(r, g, b)


def backup_file(filepath, backup_subdir):
    """Backup a file before modifying it."""
    if not os.path.exists(filepath):
        return
    dest_dir = os.path.join(BACKUP_DIR, backup_subdir)
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, os.path.basename(filepath))
    shutil.copy2(filepath, dest)


def load_theme(theme_id):
    """Load a theme JSON by ID."""
    path = os.path.join(THEME_DIR, f"{theme_id}.json")
    if not os.path.exists(path):
        print(f"ERROR: Theme '{theme_id}' not found at {path}")
        sys.exit(1)
    with open(path) as f:
        return json.load(f)


def save_current(theme_id):
    """Record the currently applied theme."""
    with open(CURRENT_FILE, "w") as f:
        f.write(theme_id + "\n")


# ── Generators ────────────────────────────────────────────────────────────────

def apply_hyprland(p):
    """Generate Hyprland colors.conf from palette."""
    if not os.path.exists(os.path.dirname(HYPRLAND_COLORS)):
        return False
    backup_file(HYPRLAND_COLORS, "hyprland")
    content = f"""# Theme: {p.get('_name', 'custom')} — generated by theme-picker

$purple   = rgb({strip_hash(p['purple'])})
$pink     = rgb({strip_hash(p['pink'])})
$red      = rgb({strip_hash(p['red'])})
$orange   = rgb({strip_hash(p['orange'])})
$yellow   = rgb({strip_hash(p['yellow'])})
$green    = rgb({strip_hash(p['green'])})
$cyan     = rgb({strip_hash(p['cyan'])})
$outline  = rgb({strip_hash(p['fg_dim'])})
$error    = rgb({strip_hash(p['red'])})
$bg       = rgb({strip_hash(p['bg'])})

general {{
  col.active_border   = $purple $pink $red $orange $yellow $green $cyan 45deg
  col.inactive_border = $outline
}}

group {{
  col.border_active   = $purple $pink $red $orange $yellow $green $cyan 45deg
  col.border_inactive = $outline
  col.border_locked_active   = $error
  col.border_locked_inactive = $outline

  groupbar {{
    col.active         = $purple
    col.inactive       = $outline
    col.locked_active   = $error
    col.locked_inactive = $outline
  }}
}}
"""
    with open(HYPRLAND_COLORS, "w") as f:
        f.write(content)
    return True


def apply_dms(p, theme_id, theme_name):
    """Generate DMS theme.json and update settings.json."""
    if not os.path.exists(DMS_THEMES_DIR):
        return False
    theme_dir = os.path.join(DMS_THEMES_DIR, theme_id)
    os.makedirs(theme_dir, exist_ok=True)

    backup_file(os.path.join(theme_dir, "theme.json"), "dms")
    backup_file(DMS_SETTINGS, "dms")

    dms_theme = {
        "id": theme_id,
        "name": theme_name,
        "version": "1.0.0",
        "author": "theme-picker",
        "description": f"{theme_name} theme generated by theme-picker",
        "dark": {
            "primary": p["accent"],
            "primaryText": p["bg"],
            "primaryContainer": darken(p["accent"], 0.3),
            "secondary": p["pink"],
            "surface": p["bg"],
            "surfaceText": p["fg"],
            "surfaceVariant": p["bg_alt"],
            "surfaceVariantText": p["fg"],
            "surfaceTint": lighten(p["bg"], 0.05),
            "background": p["bg"],
            "backgroundText": p["fg"],
            "outline": p["fg_dim"],
            "surfaceContainer": p["bg"],
            "surfaceContainerHigh": p["bg_alt"],
            "surfaceContainerHighest": lighten(p["bg_alt"], 0.1),
            "error": p["red"],
            "warning": p["yellow"],
            "info": p["blue"],
        },
        "light": {
            "primary": p["accent"],
            "primaryText": "#fafafa",
            "primaryContainer": lighten(p["accent"], 0.4),
            "secondary": p["pink"],
            "surface": "#fafafa",
            "surfaceText": p["bg"],
            "surfaceVariant": "#e5e5e6",
            "surfaceVariantText": p["bg"],
            "surfaceTint": "#f0f0f0",
            "background": "#fafafa",
            "backgroundText": p["bg"],
            "outline": "#a0a1a7",
            "surfaceContainer": "#fafafa",
            "surfaceContainerHigh": "#e5e5e6",
            "surfaceContainerHighest": "#d4d4d5",
            "error": p["red"],
            "warning": p["yellow"],
            "info": p["blue"],
        },
    }

    theme_path = os.path.join(theme_dir, "theme.json")
    with open(theme_path, "w") as f:
        json.dump(dms_theme, f, indent=2)

    # Update settings.json to point to this theme
    if os.path.exists(DMS_SETTINGS):
        with open(DMS_SETTINGS) as f:
            settings = json.load(f)
        settings["currentThemeName"] = "custom"
        settings["customThemeFile"] = theme_path
        with open(DMS_SETTINGS, "w") as f:
            json.dump(settings, f, indent=2)

    return True


def apply_noctalia(p, theme_id, theme_name):
    """Generate Noctalia colorscheme and update settings.json."""
    if not os.path.exists(NOCTALIA_SCHEMES_DIR):
        return False

    scheme_dir = os.path.join(NOCTALIA_SCHEMES_DIR, theme_name)
    os.makedirs(scheme_dir, exist_ok=True)

    scheme_path = os.path.join(scheme_dir, f"{theme_name}.json")
    backup_file(scheme_path, "noctalia")
    backup_file(NOCTALIA_SETTINGS, "noctalia")

    scheme = {
        "dark": {
            "mPrimary": p["blue"],
            "mOnPrimary": p["bg"],
            "mSecondary": p["purple"],
            "mOnSecondary": p["bg"],
            "mTertiary": p["green"],
            "mOnTertiary": p["bg"],
            "mError": p["red"],
            "mOnError": p["bg"],
            "mSurface": p["bg"],
            "mOnSurface": p["fg"],
            "mHover": p["cyan"],
            "mOnHover": p["bg"],
            "mSurfaceVariant": p["bg_alt"],
            "mOnSurfaceVariant": p["accent"],
            "mOutline": p["fg_dim"],
            "mShadow": p["bg_dark"],
            "terminal": {
                "background": p["bg"],
                "foreground": p["fg"],
                "cursor": p["accent"],
                "cursorText": p["bg"],
                "selectionBg": p["bg_alt"],
                "selectionFg": p["fg"],
                "normal": {
                    "black": p["bg"],
                    "red": p["red"],
                    "green": p["green"],
                    "yellow": p["yellow"],
                    "blue": p["blue"],
                    "magenta": p["purple"],
                    "cyan": p["cyan"],
                    "white": p["fg"],
                },
                "bright": {
                    "black": p["fg_dim"],
                    "red": lighten(p["red"], 0.15),
                    "green": lighten(p["green"], 0.15),
                    "yellow": lighten(p["yellow"], 0.15),
                    "blue": lighten(p["blue"], 0.15),
                    "magenta": lighten(p["purple"], 0.15),
                    "cyan": lighten(p["cyan"], 0.15),
                    "white": "#ffffff",
                },
            },
        },
        "light": {
            "mPrimary": darken(p["blue"], 0.2),
            "mOnPrimary": "#e8e8e8",
            "mSecondary": darken(p["purple"], 0.2),
            "mOnSecondary": "#e8e8e8",
            "mTertiary": darken(p["green"], 0.2),
            "mOnTertiary": "#e8e8e8",
            "mError": darken(p["red"], 0.2),
            "mOnError": "#fafafa",
            "mSurface": "#e8e8e8",
            "mOnSurface": p["bg"],
            "mHover": darken(p["cyan"], 0.2),
            "mOnHover": "#e8e8e8",
            "mSurfaceVariant": "#e5e5e6",
            "mOnSurfaceVariant": p["bg"],
            "mOutline": darken(p["blue"], 0.2),
            "mShadow": "#d0d0d0",
            "terminal": {
                "background": "#e8e8e8",
                "foreground": p["bg"],
                "cursor": darken(p["blue"], 0.2),
                "cursorText": "#e8e8e8",
                "selectionBg": "#d0d0d0",
                "selectionFg": p["bg"],
                "normal": {
                    "black": p["bg"],
                    "red": darken(p["red"], 0.2),
                    "green": darken(p["green"], 0.2),
                    "yellow": darken(p["yellow"], 0.2),
                    "blue": darken(p["blue"], 0.2),
                    "magenta": darken(p["purple"], 0.2),
                    "cyan": darken(p["cyan"], 0.2),
                    "white": "#e8e8e8",
                },
                "bright": {
                    "black": p["fg_dim"],
                    "red": p["red"],
                    "green": p["green"],
                    "yellow": p["yellow"],
                    "blue": p["blue"],
                    "magenta": p["purple"],
                    "cyan": p["cyan"],
                    "white": "#ffffff",
                },
            },
        },
    }

    with open(scheme_path, "w") as f:
        json.dump(scheme, f, indent=4)

    # Update settings.json predefinedScheme
    if os.path.exists(NOCTALIA_SETTINGS):
        with open(NOCTALIA_SETTINGS) as f:
            settings = json.load(f)
        if "colorSchemes" in settings:
            settings["colorSchemes"]["predefinedScheme"] = theme_name
        with open(NOCTALIA_SETTINGS, "w") as f:
            json.dump(settings, f, indent=4)

    return True


def apply_dunst(p):
    """Replace urgency color sections in dunstrc."""
    if not os.path.exists(DUNST_CONFIG):
        return False
    backup_file(DUNST_CONFIG, "dunst")

    with open(DUNST_CONFIG) as f:
        content = f.read()

    # Also update global frame_color
    content = re.sub(
        r'(^\s*frame_color\s*=\s*)".+?"',
        rf'\1"{p["blue"]}"',
        content,
        count=1,
        flags=re.MULTILINE,
    )

    # Replace urgency sections
    urgency_map = {
        "urgency_low": {
            "background": p["bg"],
            "foreground": p["fg"],
            "frame_color": p["fg_dim"],
        },
        "urgency_normal": {
            "background": p["bg"],
            "foreground": p["fg"],
            "frame_color": p["blue"],
        },
        "urgency_critical": {
            "background": p["bg"],
            "foreground": p["fg"],
            "frame_color": p["red"],
        },
    }

    for section, colors in urgency_map.items():
        for key, val in colors.items():
            pattern = rf'(\[{section}\].*?^\s*{key}\s*=\s*)".+?"'
            content = re.sub(pattern, rf'\1"{val}"', content, count=1,
                             flags=re.MULTILINE | re.DOTALL)

    with open(DUNST_CONFIG, "w") as f:
        f.write(content)
    return True


def apply_rofi(p):
    """Replace color variables in rofi config.rasi * {} block."""
    if not os.path.exists(ROFI_CONFIG):
        return False
    backup_file(ROFI_CONFIG, "rofi")

    with open(ROFI_CONFIG) as f:
        content = f.read()

    replacements = {
        "bg": hex_alpha(p["bg"], "dd"),
        "bg-alt": hex_alpha(p["bg_alt"], "ff"),
        "fg": hex_alpha(p["fg"], "ff"),
        "fg-dim": hex_alpha(p["fg_dim"], "ff"),
        "accent": hex_alpha(p["accent"], "ff"),
        "border-c": hex_alpha(p["fg_dim"], "ff"),
    }

    for var, val in replacements.items():
        # Match variable definition lines like "    bg:       #1e1e1edd;"
        pattern = rf'(^\s*{re.escape(var)}:\s*)#[0-9a-fA-F]{{6,8}};'
        content = re.sub(pattern, rf'\g<1>{val};', content, flags=re.MULTILINE)

    with open(ROFI_CONFIG, "w") as f:
        f.write(content)
    return True


def apply_swaync(p):
    """Replace @define-color block at top of SwayNC style.css."""
    if not os.path.exists(SWAYNC_CSS):
        return False
    backup_file(SWAYNC_CSS, "swaync")

    with open(SWAYNC_CSS) as f:
        content = f.read()

    new_header = f"""/* {p.get('_name', 'Custom')} theme for SwayNotificationCenter */

/* ── Base colors ── */
@define-color bg {p['bg']};
@define-color bg-dark {p['bg_dark']};
@define-color fg {p['fg']};
@define-color selection {p['bg_alt']};
@define-color comment {p['fg_dim']};
@define-color cyan {p['cyan']};
@define-color green {p['green']};
@define-color orange {p['orange']};
@define-color pink {p['pink']};
@define-color purple {p['purple']};
@define-color red {p['red']};
@define-color yellow {p['yellow']};"""

    # Replace everything from start up to (but not including) the first non-color CSS rule
    # Match: comments + @define-color lines at the start
    content = re.sub(
        r'\A(/\*.*?\*/\s*)*(/\*.*?\*/\s*)?(@define-color\s+\S+\s+#[0-9a-fA-F]+;\s*)+',
        new_header + "\n\n",
        content,
        count=1,
        flags=re.DOTALL,
    )

    with open(SWAYNC_CSS, "w") as f:
        f.write(content)
    return True


def apply_chadwm(p, theme_id):
    """Generate chadwm .h theme file and update #include in config.def.h."""
    if not os.path.exists(CHADWM_THEMES_DIR):
        return False
    backup_file(CHADWM_CONFIG, "chadwm")

    theme_file = os.path.join(CHADWM_THEMES_DIR, f"{theme_id}.h")
    backup_file(theme_file, "chadwm")

    content = f"""static const char black[]       = "{p['bg']}";
static const char white[]       = "{p['fg']}";
static const char gray2[]       = "{p['bg_alt']}"; // unfocused window border
static const char gray3[]       = "{p['fg_dim']}";
static const char gray4[]       = "{lighten(p['fg_dim'], 0.15)}";
static const char blue[]        = "{p['blue']}";  // focused window border
static const char green[]       = "{p['green']}";
static const char red[]         = "{p['red']}";
static const char orange[]      = "{p['orange']}";
static const char yellow[]      = "{p['yellow']}";
static const char pink[]        = "{p['purple']}";
static const char pinky[]       = "{p['pink']}";
static const char col_borderbar[]  = "{p['bg_dark']}"; // inner border
"""
    with open(theme_file, "w") as f:
        f.write(content)

    # Update #include in config.def.h
    if os.path.exists(CHADWM_CONFIG):
        with open(CHADWM_CONFIG) as f:
            config = f.read()

        # Comment out all theme includes, then add/uncomment the target one
        # First, comment out any active include
        config = re.sub(
            r'^(\s*)#include\s+"themes/(\w+)\.h"',
            r'\1//#include "themes/\2.h"',
            config,
            flags=re.MULTILINE,
        )
        # Check if this theme already has a commented include line
        include_pattern = rf'^(\s*)//#include\s+"themes/{re.escape(theme_id)}\.h"'
        if re.search(include_pattern, config, re.MULTILINE):
            config = re.sub(
                include_pattern,
                rf'\1#include "themes/{theme_id}.h"',
                config,
                flags=re.MULTILINE,
            )
        else:
            # Add new include after the last commented theme include
            config = re.sub(
                r'(^//#include "themes/\w+\.h"\s*\n)(?!.*?#include "themes/)',
                rf'\1#include "themes/{theme_id}.h"\n',
                config,
                count=1,
                flags=re.MULTILINE,
            )

        with open(CHADWM_CONFIG, "w") as f:
            f.write(config)

    return True


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print("Usage: apply-theme.py <theme-id> [--dry-run]")
        print(f"\nAvailable themes:")
        themes = sorted(f[:-5] for f in os.listdir(THEME_DIR) if f.endswith(".json"))
        for t in themes:
            print(f"  {t}")
        sys.exit(1)

    theme_id = sys.argv[1]
    dry_run = "--dry-run" in sys.argv

    theme = load_theme(theme_id)
    p = theme["palette"]
    p["_name"] = theme["name"]
    theme_name = theme["name"]

    # Create timestamped backup directory
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_subdir_base = f"{timestamp}_{theme_id}"
    # Override the backup_file function's subdir with timestamped one
    global BACKUP_DIR
    BACKUP_DIR = os.path.join(BASE_DIR, "backups", backup_subdir_base)
    os.makedirs(BACKUP_DIR, exist_ok=True)

    if dry_run:
        print(f"DRY RUN — would apply theme: {theme_name} ({theme_id})")
        print(f"Palette: {json.dumps(p, indent=2)}")
        return

    print(f"Applying theme: {theme_name} ({theme_id})")

    # Detect running WM
    hyprland_running = is_running("Hyprland")
    chadwm_running = is_running("chadwm")

    # Check which bar/shell is running under Hyprland
    dms_running = is_running("dms")
    noctalia_running = is_running("noctalia")

    results = []

    def _run_safe(cmd):
        """Run a command ignoring failures and timeouts."""
        try:
            subprocess.run(cmd, stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL, timeout=5)
        except (FileNotFoundError, subprocess.TimeoutExpired, subprocess.SubprocessError):
            pass

    # Always apply these
    if apply_dunst(p):
        results.append("Dunst")
        _run_safe(["pkill", "dunst"])
    if apply_rofi(p):
        results.append("Rofi")

    # Hyprland targets
    if hyprland_running:
        if apply_hyprland(p):
            results.append("Hyprland borders")
        if apply_swaync(p):
            results.append("SwayNC")
            _run_safe(["swaync-client", "-rs"])

    if dms_running or os.path.exists(DMS_THEMES_DIR):
        if apply_dms(p, theme_id, theme_name):
            results.append("DMS")

    if noctalia_running or os.path.exists(NOCTALIA_SCHEMES_DIR):
        if apply_noctalia(p, theme_id, theme_name):
            results.append("Noctalia")

    # chadwm targets
    if chadwm_running or os.path.exists(CHADWM_CONFIG):
        if apply_chadwm(p, theme_id):
            results.append("chadwm (rebuild needed: cd ~/.config/arco-chadwm/chadwm && sudo make clean install)")

    save_current(theme_id)

    print(f"\nApplied to: {', '.join(results)}")
    print(f"Backup saved to: {BACKUP_DIR}")

    if "chadwm" in str(results):
        print("\n⚠  chadwm: rebuild required!")
        print("   cd ~/.config/arco-chadwm/chadwm && sudo make clean install")
        print("   Then Super+Shift+R to reload")

    # Send notification
    _run_safe(["notify-send", "-a", "theme-picker", f"Theme: {theme_name}",
               f"Applied to: {', '.join(r.split(' (')[0] for r in results)}"])


if __name__ == "__main__":
    main()
